### ISSUE TITLE
`.` does not work with counts

### ISSUE THREAD

**Issue by chiphogg** [Julian/vim-textobj-variable-segment#10]
Consider the following testing text:

```
the_quick_brown_fox
the_quick_brown_fox
```

Position the cursor on the first `q`, and type `c2ivslow_red`.  After leaving insert mode, we have:

```
the_slow_red_fox
the_quick_brown_fox
```

Now, position the cursor on the _second_ `q`, and hit `.` (assuming you have repeat.vim installed).  The output _should_ be:

```
the_slow_red_fox
the_slow_red_fox
```

Instead, it is:

```
the_slow_red_fox
the_slow_red_brown_fox
```

In other words, the count doesn't get carried along for the repeating.

**Comment by Julian** [comment]
This seems to work now, so presumably something was fixed upstream.
