### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by draffensperger** [Julian/vim-textobj-variable-segment#15]
This is a cool plugin, thanks!

Could you please add a license to clarify how it can be used, e.g. the Vim license or Apache 2.0?

**Comment by Julian** [comment]
Hi! It's MIT,. Will add a LICENSE file.

**Comment by Julian** [comment]
Hm it looks like the COPYING file is working fine too, GitHub already lists the MIT license.

**Comment by draffensperger** [comment]
OK, great - apologies for missing that!

**Comment by Julian** [comment]
No worries
