### ISSUE TITLE
Make mapping configurable

### ISSUE THREAD

**Issue by rattletat** [Julian/vim-textobj-variable-segment#19]
Hi, 

I'm using [vimtaku/vim-textobj-keyvalue](https://github.com/vimtaku/vim-textobj-keyvalue) which already takes the `v` key. Maybe you could wrap a 

```
if exists('g:variable_segment_no_mappings')
...
endif
```
around the `textobj#user#plugin part, so ppl could just copy that bit into their vimrc and change the mapping. Maybe there is a more elegant solution to this using <Plug>

See https://github.com/kana/vim-textobj-user/issues/59

**Comment by Julian** [comment]
Seems reasonable to me.

**Comment by Julian** [comment]
Definitely willing to review a PR that does this but doubt I'll get to implementing it myself.
